# Generated by Django 6.0.1 on 2026-01-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_producto_descripcion_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_venta',
            field=models.CharField(choices=[('UNIDAD', 'Por Unidad (Ej: Alfajor)'), ('PESO', 'Por Peso/Kilo (Ej: Pan, Fiambre)')], default='UNIDAD', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
