# Generated by Django 6.0.1 on 2026-01-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_producto_tipo_venta_alter_producto_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='categoria',
            field=models.CharField(choices=[('VENTA', 'Venta Automática'), ('OTROS_INGRESOS', 'Otros Ingresos (Carga Virtual, etc)'), ('GASTO_FIJO', 'Gasto Fijo (Luz, Internet, Alquiler)'), ('GASTO_VARIO', 'Gasto Vario (Limpieza, Bolsitas)'), ('PROVEEDOR', 'Pago a Proveedores / Mercadería'), ('RETIRO_SOCIO', 'Retiro de Ganancia (Dueño)')], default='OTROS_INGRESOS', max_length=20),
        ),
    ]
