# Generated by Django 6.0.1 on 2026-01-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_movimientocaja_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='monto_credito_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédito'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='monto_debito_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Débito'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='monto_efectivo_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Efectivo'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='monto_vales_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vales y Fiados'),
        ),
        migrations.AlterField(
            model_name='sesioncaja',
            name='saldo_final_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sesioncaja',
            name='saldo_final_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
