# Generated by Django 6.0.1 on 2026-01-31 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_sesioncaja_monto_credito_real_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('deuda_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Usar para explicar faltantes o sobrantes.', null=True, verbose_name='Notas de Auditoría (Dueña)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'Mercado Pago'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('VALE', 'Vale / Fiado')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.cliente'),
        ),
    ]
