"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7k*e4)^t9+rws!@i#85^q%n(q28+_iix6uh!qfu44x@hi2ceg('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# settings.py

LANGUAGE_CODE = 'es-ar' 

TIME_ZONE = 'America/Argentina/Buenos_Aires' 

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# A dónde ir después de loguearse
LOGIN_REDIRECT_URL = 'ventas' 
# A dónde ir después de desloguearse
LOGOUT_REDIRECT_URL = 'login'

# ... al final del archivo ...

# 1. Que la sesión muera al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 2. (Opcional) Que la sesión expire sola si pasan X segundos (ej: 1 hora = 3600)
# Esto sirve por si dejan la compu prendida y se van a almorzar.
SESSION_COOKIE_AGE = 3600

# --- CONFIGURACIÓN DE JAZZMIN (DISEÑO ADMIN) ---
JAZZMIN_SETTINGS = {
    "site_title": "Kiosco Abbyta Uyuyui",
    "site_header": "Administración Kiosco",
    "site_brand": "Kiosco Abbyta Uyuyui",
    "welcome_sign": "Bienvenido al Sistema de Gestión",
    "copyright": "Kiosco Abbyta Ltd",
    "search_model": "gestion.Producto",  # Barra de búsqueda rápida arriba
    
    # Menú lateral (opcional: podés probar cambiar a True)
    "show_ui_builder": False, 

    "topmenu_links": [
        # Botón para volver al Inicio del Admin
        {"name": "Inicio Admin",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # Botón MÁGICO para ir a las Ventas
        {
            "name": "💰 IR A LA CAJA / VENTAS", 
            "url": "ventas",        # Este es el 'name' de tu url en urls.py
            "permissions": ["auth.view_user"], # Solo lo ven usuarios logueados
            "icon": "fas fa-cash-register",    # Icono de caja registradora
            "class": "btn btn-success",        # Color verde para que destaque
        },
    ],
    # ...
}